# ========= SPA redirect =========
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ========= Cache controls =========

# index.html: mai in cache -> prendi sempre l'ultima build
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Service Worker + manifest: niente cache (file non fingerprintati/critici per update)
[[headers]]
  for = "/ngsw.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/ngsw-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Bundle JS: cache lunga con immutable (hash nel filename)
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS: cache lunga
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Assets (icone, immagini, font): cache lunga
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# File di config hosting (se pubblicati): no-cache
[[headers]]
  for = "/_redirects"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/_headers"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
