name: Snapshot Classifica

on:
  schedule:
    - cron: '0 22 * * *'  # ogni giorno alle 17:00 UTC
  workflow_dispatch:      # permette anche di lanciare manualmente l'action

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Esegui snapshot
        run: curl "https://karaoke-app-6byu.onrender.com/run-snapshot?key=unaChiaveSegretissima123"